# Generated by Django 3.2.3 on 2021-06-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rega', '0002_propertyobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('seller_name', models.CharField(max_length=100)),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rega.propertyobject')),
            ],
        ),
    ]
